language: scala
scala:
  - 2.11.1
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq rethinkdb libprotobuf-dev protobuf-compiler python-software-properties
  - sudo ldconfig
before_script:
  - rethinkdb --daemon
  - rethinkdb admin set auth foobar
branches:
  only:
    - master
